### ISSUE TITLE
Extension to multiple characters

### ISSUE THREAD

**Issue by clrke** [wooorm/is-hexadecimal#1]
Suggestion to add the support for multiple characters such as:

```
var hexadecimal = require('is-hexadecimal');

hexadecimal('1A'); // true
```

**Comment by wooorm** [comment]
@cl4rke I created this library especially because it just checks one characters, which is sometimes really useful but there wasn’t anything like it. I’d like to keep this library small like this, maybe a library called something like `is-all-characters`, which takes a string and a function to check each character, might be useful though?

Anyway, closing this here as I’m not willing to add it to this module. Thanks though!
